// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package pkg

import (
	"Go-000/Week04/internal/biz"
	"Go-000/Week04/internal/data"
)

// Injectors from wire.go:

func InitializeUser() (*biz.UserBiz, error) {
	db, err := data.NewDB()
	if err != nil {
		return nil, err
	}
	dataData := data.NewData(db)
	userBiz := biz.NewBiz(dataData)
	return userBiz, nil
}
